space :=
space +=
WEBOTS_HOME_PATH=$(subst $(space),\ ,$(strip $(subst \,/,$(WEBOTS_HOME))))
C_SOURCES = my_controller3_2.c tinkerbots_utility.c
include $(WEBOTS_HOME_PATH)/resources/Makefile.include
